
services:
  # Backend Servisi
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rituals_db
      - DB_PORT=5432
      - JWT_SECRET=my_super_secret_jwt_key_change_this_in_production
      # Gmail ayarlarını buraya ekleyebilirsin veya .env dosyasından okutabilirsin
      - EMAIL_USER=ritualsapp01@gmail.com
      - EMAIL_PASS=xyle cmgd mnnr pxrf
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src # Canlı kod değişimi için (Hot Reload)
      - /backend/app/node_modules

  # Veritabanı Servisi
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rituals_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
